//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librame.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Librame.Extensions.Resources.InternalResource", typeof(InternalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid absolute uri string &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionAbsoluteUriStringFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionAbsoluteUriStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The base type &apos;{0}&apos; is not assignable from target type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionAssignableFromFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionAssignableFromFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid base path &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionBasePathFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionBasePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source type &apos;{0}&apos; cannot be cast to target type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionCastToFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionCastToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value did not pass the specified validation condition. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionDefaultValue {
            get {
                return ResourceManager.GetString("ArgumentExceptionDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file path &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionFilePathFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionFilePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The param name &apos;{0}&apos; value &apos;{1}&apos; is (equal or) greater than &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionGreaterFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionGreaterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid hex string. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionHexString {
            get {
                return ResourceManager.GetString("ArgumentExceptionHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The param name &apos;{0}&apos; value &apos;{1}&apos; is (equal or) lesser than &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentExceptionLesserFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionLesserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The param name &apos;{0}&apos; value &apos;{1}&apos; is out of range (min: &apos;{2}&apos;, max: &apos;{3}&apos;). 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionFormat {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported compressed file type (current: &apos;{0}&apos;, required: &apos;{1}&apos;). 的本地化字符串。
        /// </summary>
        internal static string FileLoadExceptionUnsupportedCompressedFileTypeFormat {
            get {
                return ResourceManager.GetString("FileLoadExceptionUnsupportedCompressedFileTypeFormat", resourceCulture);
            }
        }
    }
}
