//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librame.Extensions.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Librame.Extensions.Data.Resources.InternalResource", typeof(InternalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The change connection string is empty, cancel switch. 的本地化字符串。
        /// </summary>
        internal static string ChangeConnectionStringIsEmpty {
            get {
                return ResourceManager.GetString("ChangeConnectionStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The change connection string same as the current connection string, cancel switch. 的本地化字符串。
        /// </summary>
        internal static string ChangeConnectionStringSameAsCurrent {
            get {
                return ResourceManager.GetString("ChangeConnectionStringSameAsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current tenant &apos;{0}&apos; new connection &apos;{1}&apos; is changed. 的本地化字符串。
        /// </summary>
        internal static string ChangeNewConnectionFormat {
            get {
                return ResourceManager.GetString("ChangeNewConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close connection &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CloseConnectionFormat {
            get {
                return ResourceManager.GetString("CloseConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only supported &apos;.dll&apos; file extension. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperationExceptionCompileFileExtension {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionCompileFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find path &apos;{0}&apos; for assembly reference. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperationExceptionNotFindPathForAssemblyReferenceFormat {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionNotFindPathForAssemblyReferenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open connection &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string OpenConnectionFormat {
            get {
                return ResourceManager.GetString("OpenConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new tenant &apos;{0}&apos; is switched. 的本地化字符串。
        /// </summary>
        internal static string SwitchNewTenantFormat {
            get {
                return ResourceManager.GetString("SwitchNewTenantFormat", resourceCulture);
            }
        }
    }
}
